export const CONFIG = {
  TARGET_SPEED_BPS: 5,
  TARGET_TICK_SECONDS: 0.05,
  STRESS_EVAL_INTERVAL_TICKS: 6,
  MOVEMENT_EVAL_INTERVAL_TICKS: 2,
  STRESS_EMA_ALPHA: 0.35,
  STRESS_THRESHOLD: 0.35,
  COOLDOWN_TICKS: 18,
  MAX_SPEED_BURST: 1.2,
  MAX_ACCEL_PER_TICK_NORMAL: 0.35,
  MAX_ACCEL_PER_TICK_STRESSED: 0.12,
  ADMIN_TAG: "fh_admin",
  PREGEN: {
    DEFAULT_LENGTH_BLOCKS: 512,
    DEFAULT_WIDTH_BLOCKS: 96,
    DEFAULT_STEP_BLOCKS: 16,
    MAX_CHUNKS_PER_TICK: 3,
    PAUSE_TICK_DELTA_MS: 75,
    TICKING_RADIUS: 2,
    SAMPLE_Y: 64,
    LOG_EVERY_PERCENT: 10
  }
};
